// <auto-generated />
using System;
using CampusSmartAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusSmartAPI.Migrations
{
    [DbContext(typeof(CampusSmartDbContext))]
    [Migration("20251214165211_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusSmartAPI.Models.Area", b =>
                {
                    b.Property<int>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaID"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentAreaID")
                        .HasColumnType("int");

                    b.HasKey("AreaID");

                    b.HasIndex("ParentAreaID");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("CampusSmartAPI.Models.Device", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceID"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DeviceID");

                    b.HasIndex("Status");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CampusSmartAPI.Models.EnvironmentData", b =>
                {
                    b.Property<long>("DataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DataID"));

                    b.Property<decimal?>("CO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Noise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PM10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PM25")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WindDirection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DataID");

                    b.HasIndex("DeviceID", "RecordTime")
                        .IsDescending(false, true);

                    b.ToTable("EnvironmentData");
                });

            modelBuilder.Entity("CampusSmartAPI.Models.TrafficData", b =>
                {
                    b.Property<long>("TrafficID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TrafficID"));

                    b.Property<decimal?>("AverageSpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CongestionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrafficFlow")
                        .HasColumnType("int");

                    b.Property<string>("VehicleTypeDistribution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TrafficID");

                    b.HasIndex("DeviceID", "RecordTime")
                        .IsDescending(false, true);

                    b.ToTable("TrafficData");
                });

            modelBuilder.Entity("CampusSmartAPI.Models.WeatherData", b =>
                {
                    b.Property<long>("WeatherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WeatherID"));

                    b.Property<int?>("AirQualityIndex")
                        .HasColumnType("int");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Precipitation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("RecordTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UVIndex")
                        .HasColumnType("int");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WeatherSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WindDirection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WeatherID");

                    b.HasIndex("RecordDate");

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("CampusSmartAPI.Models.Area", b =>
                {
                    b.HasOne("CampusSmartAPI.Models.Area", "ParentArea")
                        .WithMany("ChildAreas")
                        .HasForeignKey("ParentAreaID");

                    b.Navigation("ParentArea");
                });

            modelBuilder.Entity("CampusSmartAPI.Models.EnvironmentData", b =>
                {
                    b.HasOne("CampusSmartAPI.Models.Device", "Device")
                        .WithMany("EnvironmentData")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CampusSmartAPI.Models.TrafficData", b =>
                {
                    b.HasOne("CampusSmartAPI.Models.Device", "Device")
                        .WithMany("TrafficData")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CampusSmartAPI.Models.Area", b =>
                {
                    b.Navigation("ChildAreas");
                });

            modelBuilder.Entity("CampusSmartAPI.Models.Device", b =>
                {
                    b.Navigation("EnvironmentData");

                    b.Navigation("TrafficData");
                });
#pragma warning restore 612, 618
        }
    }
}
